version: '3.8'
services:
  postgres:
    image: "postgres:13"
    environment:
      -  "POSTGRES_USER=tmp"
      -  "POSTGRES_PASSWORD=tmp"
    ports:
     - "5432:5432"
    networks:
      poc-dktedit-net:
        ipv4_address: 172.29.255.19
  api:
    image: "poc-dktedit/api"
    environment:
      - "QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/tmp"
      - "QUARKUS_LOG_LEVEL=INFO"
    ports:
     - "8080:8080"
    networks:
      poc-dktedit-net:
        ipv4_address: 172.29.255.10
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
  api_jvm:
    image: "poc-dktedit/api-jvm"
    environment:
      - "QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/tmp"
      - "QUARKUS_LOG_LEVEL=INFO"
    ports:
     - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 500M
    networks:
      poc-dktedit-net:
        ipv4_address: 172.29.255.11
networks:
  poc-dktedit-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.255.0/24
          gateway: 172.29.255.1
