# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Gradle cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew build

  docker:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Build docker images and publish
      run: echo "Need organisation docker hub infos (https://github.com/marketplace/actions/build-and-push-docker-images)"

  deploy:
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to env
      run: echo "Need organisation environment and kubernetes (multiple non Github action available)"

  sonar:
    runs-on: ubuntu-latest
    steps:
    - name: SonarCloud Scan
      run: | 
        echo "Need organisation info to set up and run Sonar Cloud (SonarSource/sonarcloud-github-action@v1.4)"
        echo "Also see if there is any problems related to modular projects"
